object Versions {
    const val compile_sdk = 28
    const val min_sdk = 16
    const val target_sdk = 27
    const val app_version_code = 102
    const val app_version_name = "2.0.0"
    const val android_plugin = "3.4.2"
    const val constraint_layout = "1.1.2"
    const val google_services = "3.0.0"
    const val lifecycle = "2.0.0"
    const val support_lib = "1.0.0"
    const val support_test = "1.1.0"
    const val multidex = "2.0.0"
    const val espresso = "3.1.0"
    const val dagger = "2.23.2"
    const val glide = "4.9.0"
    const val junit = "4.12"
    const val mockito = "2.12.0"
    const val okhttp = "4.0.0"
    const val retrofit = "2.6.0"
    const val rxjava = "2.2.10"
    const val rxandroid = "2.1.1"
    const val rxbinding = "2.0.0"
    const val findbugs = "3.0.1"
    const val paging = "2.1.0"
    const val room = "2.1.0"
    const val kotlin = "1.3.41"
    const val timber = "4.7.1"
    const val mockito_kotlin = "2.1.0"
    const val arch_core_testing = "2.0.0"
    const val robolectric = "4.3"
    const val moshi = "1.8.0"
}

object Deps {
    const val android_plugin = "com.android.tools.build:gradle:${Versions.android_plugin}"
    const val constraint_layout =
        "androidx.constraintlayout:constraintlayout:${Versions.constraint_layout}"
    const val multidex = "androidx.multidex:multidex:${Versions.multidex}"
    const val google_services = "com.google.gms:google-services:${Versions.google_services}"
    const val databinding = "com.android.databinding:compiler:${Versions.android_plugin}"

    // Support Dependencies
    const val support_lib_design = "com.google.android.material:material:${Versions.support_lib}"
    const val support_lib_appcompat = "androidx.appcompat:appcompat:${Versions.support_lib}"
    const val support_lib_recyclerview = "androidx.recyclerview:recyclerview:${Versions.support_lib}"
    const val support_lib_cardview = "androidx.cardview:cardview:${Versions.support_lib}"
    const  val support_lib_support_annotations = "androidx.annotation:annotation:{${Versions.support_lib}"

    const val lifecycle_extensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val lifecycle_compiler = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycle}"
    const val espresso_core = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val espresso_contrib = "androidx.test.espresso:espresso-contrib:${Versions.espresso}"
    const val dagger_main = "com.google.dagger:dagger:${Versions.dagger}"
    const val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val dagger_android = "com.google.dagger:dagger-android:${Versions.dagger}"
    const val dagger_android_processor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val dagger_android_support = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val glide_runtime = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glide_compiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val glide_okhttp_integration = "com.github.bumptech.glide:okhttp3-integration:${Versions.glide}"
    const val junit = "junit:junit:${Versions.junit}"
    const val okhttp_main = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttp_logging_interceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val okhttp_urlconnection = "com.squareup.okhttp:okhttp-urlconnection:${Versions.okhttp}"
    const val retrofit_main = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofit_rxjava = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val retrofit_moshi = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    const val rxjava_main = "io.reactivex.rxjava2:rxjava:${Versions.rxjava}"
    const val rxjava_android = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    const val rxbinding_platform = "com.jakewharton.rxbinding2:rxbinding:${Versions.rxbinding}"
    const val support_test_rules = "androidx.test:rules:${Versions.support_test}"
    const val support_test_runner = "androidx.test:runner:${Versions.support_test}"
    const val findbugs_jsr = "com.google.code.findbugs:jsr305:${Versions.findbugs}"
    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val kotlin_gradle_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val paging_runtime = "androidx.paging:paging-runtime:${Versions.paging}"
    const val paging_common = "androidx.paging:paging-common:${Versions.paging}"
    const val room_runtime = "androidx.room:room-runtime:${Versions.room}"
    const val room_compiler = "androidx.room:room-compiler:${Versions.room}"
    const val room_rxjava2 = "androidx.room:room-rxjava2:${Versions.room}"
    const val room_testing = "androidx.room:room-testing:${Versions.room}"
    const val moshi_kotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val moshi_codegen = "com.squareup.moshi:moshi-kotlin-codegen:${Versions.moshi}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val arch_core_testing = "androidx.arch.core:core-testing:${Versions.arch_core_testing}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"

    const val mockito_core = "org.mockito:mockito-core:${Versions.mockito}"
    const val mockito_android = "org.mockito:mockito-android:${Versions.mockito}"
    const val mockito_kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockito_kotlin}"
    const val mockito_inline = "org.mockito:mockito-inline:${Versions.mockito}"
}