object Versions {
    const val compile_sdk = 26
    const val min_sdk = 16
    const val target_sdk = 26
    const val app_version_code = 102
    const val app_version_name = "2.0.0"
    const val android_plugin = "3.4.2"
    const val constraint_layout = "1.0.2"
    const val google_services = "3.0.0"
    const val lifecycle = "1.1.1"
    const val support_lib = "27.1.0"
    const val support_test = "1.0.1"
    const val multidex = "1.0.1"
    const val espresso = "2.2.2"
    const val dagger = "2.23.2"
    const val glide = "4.9.0"
    const val gson = "2.8.2"
    const val junit = "4.12"
    const val mockito = "2.12.0"
    const val okhttp = "4.0.0"
    const val okhttp_urlconnection = "2.7.5"
    const val retrofit = "2.2.0"
    const val rxjava = "2.2.10"
    const val rxandroid = "2.1.1"
    const val rxbinding = "2.0.0"
    const val findbugs = "3.0.1"
    const val auto_value = "1.6"
    const val auto_value_gson = "0.7.0"
    const val auto_value_parcel = "0.2.5"
    const val paging = "1.0.0"
    const val room = "1.1.1"
    const val kotlin = "1.3.41"
    const val timber = "4.7.1"
    const val mockito_kotlin = "2.1.0"
    const val arch_core_testing = "1.1.1"
    const val robolectric = "4.3"
    const val moshi = "1.8.0"
}

object Deps {
    const val android_plugin = "com.android.tools.build:gradle:${Versions.android_plugin}"
    const val constraint_layout =
        "com.android.support.constraint:constraint-layout:${Versions.constraint_layout}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val google_services = "com.google.gms:google-services:${Versions.google_services}"

    // Support Dependencies
    const val support_lib_design = "com.android.support:design:${Versions.support_lib}"
    const val support_lib_appcompat = "com.android.support:appcompat-v7:${Versions.support_lib}"
    const val support_lib_support_v4 = "com.android.support:support-v4:${Versions.support_lib}"
    const val support_lib_recyclerview = "com.android.support:recyclerview-v7:${Versions.support_lib}"
    const val support_lib_cardview = "com.android.support:cardview-v7:${Versions.support_lib}"
    const  val support_lib_support_annotations =
        "com.android.support:support-annotations:{${Versions.support_lib}"

    const val lifecycle_extensions = "android.arch.lifecycle:extensions:${Versions.lifecycle}"
    const val lifecycle_compiler = "android.arch.lifecycle:common-java8:${Versions.lifecycle}"
    const val espresso_core = "com.android.support.test.espresso:espresso-core:${Versions.espresso}"
    const val espresso_contrib = "com.android.support.test.espresso:espresso-contrib:${Versions.espresso}"
    const val dagger_main = "com.google.dagger:dagger:${Versions.dagger}"
    const val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val dagger_android = "com.google.dagger:dagger-android:${Versions.dagger}"
    const val dagger_android_processor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val dagger_android_support = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val glide_runtime = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glide_compiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val glide_okhttp_integration = "com.github.bumptech.glide:okhttp3-integration:${Versions.glide}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val junit = "junit:junit:${Versions.junit}"
    const val okhttp_main = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttp_logging_interceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val okhttp_urlconnection = "com.squareup.okhttp:okhttp-urlconnection:${Versions.okhttp}"
    const val retrofit_main = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofit_rxjava = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val retrofit_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val rxjava_main = "io.reactivex.rxjava2:rxjava:${Versions.rxjava}"
    const val rxjava_android = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    const val rxbinding_platform = "com.jakewharton.rxbinding2:rxbinding:${Versions.rxbinding}"
    const val rxbinding_support_v4 = "com.jakewharton.rxbinding2:rxbinding-support-v4:${Versions.rxbinding}"
    const val rxbinding_support_v7 = "com.jakewharton.rxbinding2:rxbinding-appcompat-v7:${Versions.rxbinding}"
    const val support_test_rules = "com.android.support.test:rules:${Versions.support_test}"
    const val support_test_runner = "com.android.support.test:runner:${Versions.support_test}"
    const val findbugs_jsr = "com.google.code.findbugs:jsr305:${Versions.findbugs}"
    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val kotlin_gradle_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val auto_value_annotations = "com.google.auto.value:auto-value-annotations:${Versions.auto_value}"
    const val auto_value_compiler = "com.google.auto.value:auto-value:${Versions.auto_value}"
    const val auto_value_gson_compiler = "com.ryanharter.auto.value:auto-value-gson:${Versions.auto_value_gson}"
    const val auto_value_gson_annotations = "com.ryanharter.auto.value:auto-value-gson-annotations:${Versions.auto_value_gson}"
    const val auto_value_parcel = "com.ryanharter.auto.value:auto-value-parcel:${Versions.auto_value_parcel}"
    const val paging_runtime = "android.arch.paging:runtime:${Versions.paging}"
    const val paging_common = "android.arch.paging:common:${Versions.paging}"
    const val room_runtime = "android.arch.persistence.room:runtime:${Versions.room}"
    const val room_compiler = "android.arch.persistence.room:compiler:${Versions.room}"
    const val room_rxjava2 = "android.arch.persistence.room:rxjava2:${Versions.room}"
    const val room_testing = "android.arch.persistence.room:testing:${Versions.room}"
    const val moshi_kotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val moshi_codegen = "com.squareup.moshi:moshi-kotlin-codegen:${Versions.moshi}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val arch_core_testing = "android.arch.core:core-testing:${Versions.arch_core_testing}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"
    const val mockito_core = "org.mockito:mockito-core:${Versions.mockito}"
    const val mockito_android = "org.mockito:mockito-android:${Versions.mockito}"
    const val mockito_kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockito_kotlin}"
}